version: '3'

services:
  pdf_email.service:
    build:
      context: .
      dockerfile: Dockerfile
    image: service_local_pdf_email
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - ./.env